# Generated by Django 2.2 on 2019-04-02 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Capsule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=250)),
                ('emails', models.CharField(blank=True, max_length=2500)),
                ('capsule_type', models.CharField(choices=[('F', 'FREE'), ('P', 'PREMIUM'), ('M', 'MODULAR')], max_length=1)),
                ('private', models.BooleanField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=7, null=True)),
                ('dead_man_switch', models.BooleanField()),
                ('dead_man_counter', models.BigIntegerField()),
                ('dead_man_initial_counter', models.BigIntegerField()),
                ('time_unit', models.IntegerField(choices=[(0, 'minutes'), (1, 'days'), (2, 'months'), (3, 'years')], null=True)),
                ('twitter', models.BooleanField()),
                ('facebook', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=250)),
                ('release_date', models.DateTimeField()),
                ('release_notify', models.BooleanField(default=False)),
                ('capsule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='main.Capsule')),
            ],
        ),
    ]
